<p>April 29, 2015</p>
<table cellspacing="1" cellpadding="2" width="100%" class="nd-report">
  <colgroup>
    <col style="width: 20%;" />
    <col style="width: 20%;" />
    <col style="width: 20%;" />
    <col style="width: 20%;" />
    <col style="width: 20%;" />
  </colgroup>
  <tr valign="top">
    <td>
    </td>
    <td class="header-right">Active</td>
    <td class="header-right">Down</td>
    <td class="header-right">Total</td>
    <td class="header-right">% Active</td>
  </tr>
  <tr valign="top">
    <td class="header-left" colspan="5">Western Canada</td>
  </tr>
  <tr valign="top">
    <td>AB</td>
    <td class="count" align="right">52</td>
    <td class="count" align="right">475</td>
    <td class="count" align="right">527</td>
    <td class="percent" align="right">10%</td>
  </tr>
  <tr valign="top">
    <td>SK</td>
    <td class="count" align="right">5</td>
    <td class="count" align="right">127</td>
    <td class="count" align="right">132</td>
    <td class="percent" align="right">4%</td>
  </tr>
  <tr valign="top">
    <td>BC</td>
    <td class="count" align="right">24</td>
    <td class="count" align="right">57</td>
    <td class="count" align="right">81</td>
    <td class="percent" align="right">30%</td>
  </tr>
  <tr valign="top">
    <td>MB</td>
    <td class="count" align="right">-</td>
    <td class="count" align="right">15</td>
    <td class="count" align="right">15</td>
    <td class="percent" align="right">0%</td>
  </tr>
  <tr valign="top">
    <td class="header-left">WC Total</td>
    <td class="count-bold" align="right">81</td>
    <td class="count-bold" align="right">674</td>
    <td class="count-bold" align="right">755</td>
    <td class="percent-bold" align="right">11%</td>
  </tr>
  <tr valign="top">
    <td class="header-left" colspan="5">Eastern Canada</td>
  </tr>
  <tr valign="top">
    <td>QC</td>
    <td class="count" align="right">-</td>
    <td class="count" align="right">1</td>
    <td class="count" align="right">1</td>
    <td class="percent" align="right">0%</td>
  </tr>
  <tr valign="top">
    <td class="header-left">Canada</td>
    <td class="count-bold" align="right">81</td>
    <td class="count-bold" align="right">675</td>
    <td class="count-bold" align="right">756</td>
    <td class="percent-bold" align="right">11%</td>
  </tr>
</table>