<div>
  <div class="nd-par">April 13, 2015</div>
  <table class="nd-report" width="100%" cellspacing="1" cellpadding="2">
    <thead>
      <tr valign="top">
        <td>
        </td>
        <td class="header-right" align="right">Drilling</td>
        <td class="header-right" align="right">Down</td>
        <td class="header-right" align="right">Total</td>
        <td class="header-right" align="right">Util.</td>
      </tr>
    </thead>
    <tbody>
      <tr valign="top">
        <td>
          <span style="color: rgb(51, 51, 51);">AB</span>
        </td>
        <td class="count" align="right">49</td>
        <td class="count" align="right">478</td>
        <td class="count" align="right">527</td>
        <td class="count" align="right">
          <span style="color: rgb(51, 51, 51);">9%</span>
        </td>
      </tr>
      <tr valign="top">
        <td>
          <span style="color: rgb(51, 51, 51);">BC</span>
        </td>
        <td class="count" align="right">
          <span style="color: rgb(51, 51, 51);">25</span>
        </td>
        <td class="count" align="right">57</td>
        <td class="count" align="right">82</td>
        <td class="count" align="right">
          <span style="color: rgb(51, 51, 51);">31%</span>
        </td>
      </tr>
      <tr valign="top">
        <td>
          <span style="color: rgb(51, 51, 51);">MB</span>
        </td>
        <td class="count" align="right">-</td>
        <td class="count" align="right">15</td>
        <td class="count" align="right">
          <span style="color: rgb(51, 51, 51);">15</span>
        </td>
        <td class="count" align="right">
          <span style="color: rgb(51, 51, 51);">0%</span>
        </td>
      </tr>
      <tr valign="top">
        <td>
          <span style="color: rgb(51, 51, 51);">SK</span>
        </td>
        <td class="count" align="right">5</td>
        <td class="count" align="right">126</td>
        <td class="count" align="right">
          <span style="color: rgb(51, 51, 51);">131</span>
        </td>
        <td class="count" align="right">
          <span style="color: rgb(51, 51, 51);">4%</span>
        </td>
      </tr>
      <tr valign="top">
        <td>
          <span style="color: rgb(51, 51, 51);">EC</span>
        </td>
        <td class="count" align="right">-</td>
        <td class="count" align="right">
          <span style="color: rgb(51, 51, 51);">2</span>
        </td>
        <td class="count" align="right">
          <span style="color: rgb(51, 51, 51);">2</span>
        </td>
        <td class="count" align="right">
          <span style="color: rgb(51, 51, 51);">0%</span>
        </td>
      </tr>
      <tr valign="top">
        <td>
          <span style="color: rgb(51, 51, 51);">NT</span>
        </td>
        <td class="count" align="right">-</td>
        <td class="count" align="right">
          <span style="color: rgb(51, 51, 51);">0</span>
        </td>
        <td class="count" align="right">
          <span style="color: rgb(51, 51, 51);">0</span>
        </td>
        <td class="count" align="right">
          <span style="color: rgb(51, 51, 51);">0%</span>
        </td>
      </tr>
      <tr valign="top">
        <td>
          <strong>
            <span style="color: rgb(51, 51, 51);">Total</span>
          </strong>
        </td>
        <td class="count" align="right">79</td>
        <td class="count" align="right">
          <strong>
            <span style="color: rgb(51, 51, 51);">678</span>
          </strong>
        </td>
        <td class="count" align="right">
          <strong>
            <span style="color: rgb(51, 51, 51);">757</span>
          </strong>
        </td>
        <td class="count" align="right">
          <strong>
            <span style="color: rgb(51, 51, 51);">10%</span>
          </strong>
        </td>
      </tr>
      <tr valign="top">
        <td>
          <strong>
            <span style="color: rgb(51, 51, 51);">Last Year</span>
          </strong>
        </td>
        <td class="count" align="right">
          <strong>
            <span style="color: rgb(51, 51, 51);">202</span>
          </strong>
        </td>
        <td class="count" align="right">
          <strong>
            <span style="color: rgb(51, 51, 51);">608</span>
          </strong>
        </td>
        <td class="count" align="right">
          <strong>
            <span style="color: rgb(51, 51, 51);">810</span>
          </strong>
        </td>
        <td class="count" align="right">
          <strong>
            <span style="color: rgb(51, 51, 51);">25%</span>
          </strong>
        </td>
      </tr>
    </tbody>
  </table>
</div>