<div class="toc">Enserco Agrees To Nabors’ Takeover Offer</div>
<div class="feature">Enserco Energy Service Company Inc. said today it has agreed to an acquisition offer worth $15.50 (Cdn.) per share from Nabors Industries, Inc. and will become the second Canadian drilling contractor acquired by the global, Houston-based corporation in the last few months.</div>
<div class="sub"><a href="brn.asp">more...</a></div>
