
    <table cellspacing="1" cellpadding="2" width="100%" class="nd-report">
      <tr>
        <td height="0" width="77.777777777777771%" style="border: 0px;" />
        <td height="0" width="22.222222222222221%" style="border: 0px;" />
      </tr>
      <tr valign="top">
        <td class="header">Operator</td>
        <td class="header-right">Active Rigs</td>
      </tr>
      <tr valign="top">
        <td>Progress Energy Canada Ltd.</td>
        <td class="count" align="right">9</td>
      </tr>
      <tr valign="top">
        <td>Royal Dutch Shell plc</td>
        <td class="count" align="right">8</td>
      </tr>
      <tr valign="top">
        <td>Seven Generations Energy Ltd.</td>
        <td class="count" align="right">7</td>
      </tr>
      <tr valign="top">
        <td>Peyto Exploration &amp; Development Corp.</td>
        <td class="count" align="right">6</td>
      </tr>
      <tr valign="top">
        <td>Encana Corporation</td>
        <td class="count" align="right">5</td>
      </tr>
    </table>
