<h2>
February 2002
</h2>
<table border cellspacing = 0 cellpadding=2 cols=7 width="100%" align=center class="report"><tr align=center>
<th width="14%">Sun</th>
<th width="14%">Mon</th>
<th width="14%">Tue</th>
<th width="14%">Wed</th>
<th width="14%">Thu</th>
<th width="14%">Fri</th>
<th width="14%">Sat</th></tr>
<tr align=center><td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td><font color=#CCCCCC>1</font></td>
<td><font color=#CCCCCC>2</font></td>
</tr><tr align=center>
<td><font color=#CCCCCC>3</font></td>
<td><font color=#CCCCCC>4</font></td>
<td><font color=#CCCCCC>5</font></td>
<td><font color=#CCCCCC>6</font></td>
<td><font color=#CCCCCC>7</font></td>
<td><font color=#CCCCCC>8</font></td>
<td><font color=#CCCCCC>9</font></td>
</tr><tr align=center>
<td><font color=#CCCCCC>10</font></td>
<td><font color=#CCCCCC>11</font></td>
<td><font color=#CCCCCC>12</font></td>
<td><font color=#CCCCCC>13</font></td>
<td><font color=#CCCCCC>14</font></td>
<td><font color=#CCCCCC>15</font></td>
<td><font color=#CCCCCC>16</font></td>
</tr><tr align=center>
<td><font color=#CCCCCC>17</font></td>
<td><font color=#CCCCCC>18</font></td>
<td><font color=#CCCCCC>19</font></td>
<td><font color=#CCCCCC>20</font></td>
<td><font color=#CCCCCC>21</font></td>
<td><font color=#CCCCCC>22</font></td>
<td><font color=#CCCCCC>23</font></td>
</tr><tr align=center>
<td><font color=#CCCCCC>24</font></td>
<td><font color=#CCCCCC>25</font></td>
<td><font color=#CCCCCC>26</font></td>
<td><font color=#CCCCCC>27</font></td>
<td><font color=#CCCCCC>28</font></td>
<td>&nbsp;</td><td>&nbsp;</td></tr></table><br>
<h2>
January 2002
</h2>
<table border cellspacing = 0 cellpadding=2 cols=7 width="100%" align=center class="report"><tr align=center>
<th width="14%">Sun</th>
<th width="14%">Mon</th>
<th width="14%">Tue</th>
<th width="14%">Wed</th>
<th width="14%">Thu</th>
<th width="14%">Fri</th>
<th width="14%">Sat</th></tr>
<tr align=center><td>&nbsp;</td>
<td>&nbsp;</td>
<td><font color=#CCCCCC>1</font></td>
<td><a href="dateresults.asp?date=January+2%2C+2002">2</a></td>
<td><a href="dateresults.asp?date=January+3%2C+2002">3</a></td>
<td><a href="dateresults.asp?date=January+4%2C+2002">4</a></td>
<td><font color=#CCCCCC>5</font></td>
</tr><tr align=center>
<td><font color=#CCCCCC>6</font></td>
<td><a href="dateresults.asp?date=January+7%2C+2002">7</a></td>
<td><a href="dateresults.asp?date=January+8%2C+2002">8</a></td>
<td><font color=#CCCCCC>9</font></td>
<td><font color=#CCCCCC>10</font></td>
<td><font color=#CCCCCC>11</font></td>
<td><font color=#CCCCCC>12</font></td>
</tr><tr align=center>
<td><font color=#CCCCCC>13</font></td>
<td><font color=#CCCCCC>14</font></td>
<td><font color=#CCCCCC>15</font></td>
<td><font color=#CCCCCC>16</font></td>
<td><font color=#CCCCCC>17</font></td>
<td><font color=#CCCCCC>18</font></td>
<td><font color=#CCCCCC>19</font></td>
</tr><tr align=center>
<td><font color=#CCCCCC>20</font></td>
<td><font color=#CCCCCC>21</font></td>
<td><font color=#CCCCCC>22</font></td>
<td><font color=#CCCCCC>23</font></td>
<td><font color=#CCCCCC>24</font></td>
<td><font color=#CCCCCC>25</font></td>
<td><font color=#CCCCCC>26</font></td>
</tr><tr align=center>
<td><font color=#CCCCCC>27</font></td>
<td><font color=#CCCCCC>28</font></td>
<td><font color=#CCCCCC>29</font></td>
<td><font color=#CCCCCC>30</font></td>
<td><font color=#CCCCCC>31</font></td>
<td>&nbsp;</td><td>&nbsp;</td></tr></table><br>
<h2>
December 2001
</h2>
<table border cellspacing = 0 cellpadding=2 cols=7 width="100%" align=center class="report"><tr align=center>
<th width="14%">Sun</th>
<th width="14%">Mon</th>
<th width="14%">Tue</th>
<th width="14%">Wed</th>
<th width="14%">Thu</th>
<th width="14%">Fri</th>
<th width="14%">Sat</th></tr>
<tr align=center><td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td><font color=#CCCCCC>1</font></td>
</tr><tr align=center>
<td><font color=#CCCCCC>2</font></td>
<td><a href="dateresults.asp?date=December+3%2C+2001">3</a></td>
<td><a href="dateresults.asp?date=December+4%2C+2001">4</a></td>
<td><a href="dateresults.asp?date=December+5%2C+2001">5</a></td>
<td><a href="dateresults.asp?date=December+6%2C+2001">6</a></td>
<td><a href="dateresults.asp?date=December+7%2C+2001">7</a></td>
<td><font color=#CCCCCC>8</font></td>
</tr><tr align=center>
<td><font color=#CCCCCC>9</font></td>
<td><a href="dateresults.asp?date=December+10%2C+2001">10</a></td>
<td><a href="dateresults.asp?date=December+11%2C+2001">11</a></td>
<td><a href="dateresults.asp?date=December+12%2C+2001">12</a></td>
<td><a href="dateresults.asp?date=December+13%2C+2001">13</a></td>
<td><a href="dateresults.asp?date=December+14%2C+2001">14</a></td>
<td><font color=#CCCCCC>15</font></td>
</tr><tr align=center>
<td><font color=#CCCCCC>16</font></td>
<td><a href="dateresults.asp?date=December+17%2C+2001">17</a></td>
<td><a href="dateresults.asp?date=December+18%2C+2001">18</a></td>
<td><a href="dateresults.asp?date=December+19%2C+2001">19</a></td>
<td><a href="dateresults.asp?date=December+20%2C+2001">20</a></td>
<td><a href="dateresults.asp?date=December+21%2C+2001">21</a></td>
<td><font color=#CCCCCC>22</font></td>
</tr><tr align=center>
<td><font color=#CCCCCC>23</font></td>
<td><a href="dateresults.asp?date=December+24%2C+2001">24</a></td>
<td><font color=#CCCCCC>25</font></td>
<td><font color=#CCCCCC>26</font></td>
<td><a href="dateresults.asp?date=December+27%2C+2001">27</a></td>
<td><a href="dateresults.asp?date=December+28%2C+2001">28</a></td>
<td><font color=#CCCCCC>29</font></td>
</tr><tr align=center>
<td><font color=#CCCCCC>30</font></td>
<td><a href="dateresults.asp?date=December+31%2C+2001">31</a></td>
<td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr></table><br>
<h2>
November 2001
</h2>
<table border cellspacing = 0 cellpadding=2 cols=7 width="100%" align=center class="report"><tr align=center>
<th width="14%">Sun</th>
<th width="14%">Mon</th>
<th width="14%">Tue</th>
<th width="14%">Wed</th>
<th width="14%">Thu</th>
<th width="14%">Fri</th>
<th width="14%">Sat</th></tr>
<tr align=center><td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td><a href="dateresults.asp?date=November+1%2C+2001">1</a></td>
<td><a href="dateresults.asp?date=November+2%2C+2001">2</a></td>
<td><font color=#CCCCCC>3</font></td>
</tr><tr align=center>
<td><font color=#CCCCCC>4</font></td>
<td><a href="dateresults.asp?date=November+5%2C+2001">5</a></td>
<td><a href="dateresults.asp?date=November+6%2C+2001">6</a></td>
<td><a href="dateresults.asp?date=November+7%2C+2001">7</a></td>
<td><a href="dateresults.asp?date=November+8%2C+2001">8</a></td>
<td><a href="dateresults.asp?date=November+9%2C+2001">9</a></td>
<td><font color=#CCCCCC>10</font></td>
</tr><tr align=center>
<td><font color=#CCCCCC>11</font></td>
<td><font color=#CCCCCC>12</font></td>
<td><a href="dateresults.asp?date=November+13%2C+2001">13</a></td>
<td><a href="dateresults.asp?date=November+14%2C+2001">14</a></td>
<td><a href="dateresults.asp?date=November+15%2C+2001">15</a></td>
<td><a href="dateresults.asp?date=November+16%2C+2001">16</a></td>
<td><font color=#CCCCCC>17</font></td>
</tr><tr align=center>
<td><font color=#CCCCCC>18</font></td>
<td><a href="dateresults.asp?date=November+19%2C+2001">19</a></td>
<td><a href="dateresults.asp?date=November+20%2C+2001">20</a></td>
<td><a href="dateresults.asp?date=November+21%2C+2001">21</a></td>
<td><a href="dateresults.asp?date=November+22%2C+2001">22</a></td>
<td><a href="dateresults.asp?date=November+23%2C+2001">23</a></td>
<td><font color=#CCCCCC>24</font></td>
</tr><tr align=center>
<td><font color=#CCCCCC>25</font></td>
<td><a href="dateresults.asp?date=November+26%2C+2001">26</a></td>
<td><a href="dateresults.asp?date=November+27%2C+2001">27</a></td>
<td><a href="dateresults.asp?date=November+28%2C+2001">28</a></td>
<td><a href="dateresults.asp?date=November+29%2C+2001">29</a></td>
<td><a href="dateresults.asp?date=November+30%2C+2001">30</a></td>
<td>&nbsp;</td></tr></table><br>

