<div> 
    <!--#include virtual="/common/footer/footer.ascx"--> 
</div>
</div>
</div>
<script type="text/javascript">
      var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
      document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
    </script> 
<script type="text/javascript">
      try {
      var pageTracker = _gat._getTracker("UA-6217271-15");
      pageTracker._trackPageview();
      } catch(err) {}
    </script> 

<!-- jQuery --> 
<script src="js/jquery.js"></script> 

<!-- Bootstrap Core JavaScript --> 
<script src="js/bootstrap.min.js"></script> 

<!-- Plugin JavaScript --> 
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script> 
<script src="js/classie.js"></script> 

<!-- Custom JavaScript --> 
<script src="js/scripts.js"></script>

</body></html>
