<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<title><% = title %></title>

<!-- Bootstrap Core CSS -->
<link href="css/bootstrap.css" rel="stylesheet">
<!-- Custom CSS -->
<link rel="stylesheet" href="/common/footer/footer121109.css" />
<link href="css/main.css" rel="stylesheet">
<!-- Custom Fonts -->
<link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  <script type="text/javascript">
    (function() {
       var useSSL = 'https:' == document.location.protocol;
       var src = (useSSL ? 'https:' : 'http:') +
                  '//www.googletagservices.com/tag/js/gpt.js';
       document.write('<scr' + 'ipt src="' + src + '"></scr' + 'ipt>');
     })();
  </script>
  <script type="text/javascript">
    googletag.defineSlot('/4326737/JWNWS_JWN_jwn-site_jwn-section_jwn-subsection_728x90_S1_RON_JWN-network', [728, 90], 'div-gpt-ad-1329923512779-13').addService(googletag.pubads())
    .setTargeting("publisher", "JWN")
    .setTargeting("site", "RIGW")
    .setTargeting("section", "homepage");

    googletag.defineSlot('/4326737/JWNWS_JWN_jwn-site_jwn-section_jwn-subsection_228x90_S1_RON_JWN-network', [228, 90], 'div-gpt-ad-1329923512779-9').addService(googletag.pubads())
    .setTargeting("publisher", "JWN")
    .setTargeting("site", "RIGW")
    .setTargeting("section", "homepage");

    googletag.defineSlot('/4326737/JWNWS_JWN_jwn-site_jwn-section_jwn-subsection_300x250_S1_RON_JWN-network', [300, 250], 'div-gpt-ad-1329923512779-10').addService(googletag.pubads())
    .setTargeting("publisher", "JWN")
    .setTargeting("site", "RIGW")
    .setTargeting("section", "homepage");

    googletag.defineSlot('/4326737/JWNWS_JWN_jwn-site_jwn-section_jwn-subsection_160x600_S1_RON_JWN-network', [160, 600], 'div-gpt-ad-1329923512779-3').addService(googletag.pubads())
    .setTargeting("publisher", "JWN")
    .setTargeting("site", "RIGW")
    .setTargeting("section", "homepage");

    googletag.defineSlot('/4326737/JWNWS_JWN_jwn-site_jwn-section_jwn-subsection_300x120_S1_RON_JWN-network', [300, 120], 'div-gpt-ad-1335301288326-2').addService(googletag.pubads())
    .setTargeting("publisher", "JWN")
    .setTargeting("site", "RIGW")
    .setTargeting("section", "homepage");

    googletag.pubads().enableSyncRendering();
    googletag.pubads().enableSingleRequest();
    googletag.enableServices();
  </script>
</head>
<body id="page-top" class="index">
<!-- Header -->
<header>
      <div class="mainNav sub-page">
        <div class="leaderboard-holder">
              <div class="container"><img src="img/leaderboard.jpg" alt="Leaderboard"/> </div>
          </div>
        <div class="utilityNavWrap">
              <div class="utilityNav"> 
                <!-- Navigation -->
                <nav class="navbar navbar-utility navbar-static-top utility-subpage">
                      <div class="container"> 
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse bs-example-navbar-collapse-1">
                              <ul class="nav navbar-nav navbar-right">
                                <li class="hidden"> <a href="#page-top"></a> </li>
                                <li> <a href="#">My Profile</a> </li>
                                <li> <a href="https://secure.junewarren-nickles.com/corp-accounts.aspx" target="_blank">Corporate Accounts</a> </li>
                                <li> <a class="page-scroll" href="#">About Us</a> </li>
						  <li> <a href="#">Contact Us</a> </li>
                            </ul>
                          </div>
                        <!-- /.navbar-collapse --> 
                    </div>
                      <!-- /.container-fluid --> 
                  </nav>
            </div>
          </div>
        <!-- Navigation -->
        
        <nav class="navbar navbar-default navbar-static-top nav-subpage">
              <div class="container"> 
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header page-scroll">
                      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                      <a class="navbar-brand page-scroll" href="index.asp"></a> </div>
                
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse bs-example-navbar-collapse-1">
                      <ul class="nav navbar-nav navbar-right navbar-buttons">
                        <li> <a class="page-scroll" href="#">Logout</a> </li>
                    </ul>
                      <ul class="nav navbar-nav navbar-right navbar-home">
                        <li class="hidden"> <a href="#page-top"></a> </li>
                        
                        <li> <a class="page-scroll" href="../data.asp">Rig Locator Data</a> </li>
				    <li> <a class="page-scroll" href="#">Rig Locator Map</a> </li>
                        <li> <a class="page-scroll" href="alerts.asp">Email Alerts</a> </li>
                        <li class="dropdown"> <a class="page-scroll" href="#team" class="dropdown-toggle" data-toggle="dropdown">Drilling Rig Reports</a>
                              <ul class="dropdown-menu">
                                <li><a href="#">Contractors' Summary</a></li>
                                <li><a href="#">Top Operators</a></li>
                                <li><a href="#">Depth Activity</a></li>
                                <li><a href="#">Planned Drilling Projects</a></li>
                                <li><a href="#">Drilling Activity Surveys</a></li>
						  <li><a href="#">Western Canada Drilling Chart</a></li>
						  <li><a href="#">Contractor Utilization Summary</a></li>
						  <li><a href="#">Download and print reports</a></li>
                            </ul>
                          </li>
                        <li> <a class="page-scroll" href="#">Drilling Summary</a> </li>
                        
                    </ul>
                  </div>
                <!-- /.navbar-collapse --> 
            </div>
              <!-- /.container-fluid --> 
          </nav>
    </div>
  </header>