<!-- Begin Ban Man Pro Banner Code -  Site: Nickles  Zone: OPM Rig Locator -->
<SCRIPT LANGUAGE="JAVASCRIPT">
<!--
var browName = navigator.appName;
var browDateTime = (new Date()).getTime();
var browVersion = parseInt(navigator.appVersion);
var ua=navigator.userAgent.toLowerCase();
var adcode='';
if (browName=='Netscape'){
     if (browVersion>=5) 
          { document.write('<ifr'+'ame src="http://www.nickles.com/banman/banman.asp?ZoneID=34&Task=Get&Browser=NETSCAPE6&SiteID=1&X=' + browDateTime + '" width=120 height=60 Marginwidth=0 Marginheight=0 Hspace=0 Vspace=0 Frameborder=0 Scrolling=No></ifr'+'ame>'); }
     else if ((browVersion>=4)&&(ua.indexOf("mac")==-1))
          { document.write('<S'+'CRIPT src="http://www.nickles.com/banman/banman.asp?ZoneID=34&Task=Get&Browser=NETSCAPE4&SiteID=1">');
          document.write('</'+'scr'+'ipt>');
          document.write(adcode); }
     else if (browVersion>=3) 
          { document.write('<A HREF="http://www.nickles.com/banman/banman.asp?ZoneID=34&Task=Click&Mode=HTML&SiteID=1&PageID=' + browDateTime + '&RandomNumber=' + browDateTime + '" target="_new"><IMG SRC="http://www.nickles.com/banman/banman.asp?ZoneID=34&Task=Get&Mode=HTML&SiteID=1&PageID=' + browDateTime + '&RandomNumber=' + browDateTime + '" width="120" height="60" border="0"></A>'); } }
if (browName=='Microsoft Internet Explorer')
     { document.write('<ifr'+'ame src="http://www.nickles.com/banman/banman.asp?ZoneID=34&Task=Get&SiteID=1&X=' + browDateTime + '" width=120 height=60 Marginwidth=0 Marginheight=0 Hspace=0 Vspace=0 Frameborder=0 Scrolling=No></ifr'+'ame>'); }
// --> 
</script>
<noscript>
    <a href="http://www.nickles.com/banman/banman.asp?ZoneID=34&Task=Click&Mode=HTML&SiteID=1&PageID=43143" target="_new">
    <img src="http://www.nickles.com/banman/banman.asp?ZoneID=34&Task=Get&Mode=HTML&SiteID=1&PageID=43143" width="120" height="60" border="0"></a>
</noscript>
<!-- End Ban Man Pro Banner Code -  Site: Nickles  Zone: OPM Rig Locator -->
