</div>
<p class="dateline" align="center" style="color: #666666;">All data available
through JuneWarren-Nickle's Energy Group Rig Locator is copyrighted.<br>Subscribers must not reproduce,
publish, distribute or store data in any manner without consent.</p>

<div id="lower-menu" class="menu-text">
<a href="/">Rig Home</a> |
<a href="/search.asp">Search Drilling Rigs</a> |
<a href="/common/contact.asp">Contact Us</a> |
<a href="/help.asp">Help</a>
</div>

<div id="footer-block" class="dateline" style="text-align: center;">
 &copy; <% = Year(Date) %>
<a href="/common/copyright.asp">Copyright JuneWarren-Nickle's Energy Group</a>. All rights reserved.<br>
<a href="/common/disclaimer.asp">Disclaimer</a> |
<a href="/common/privacy.asp">Privacy Policy</a> |
<a href="/common/comments.asp">Comments</a></div></td>
</div>
<script type="text/javascript">
  var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
  document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
  try {
  var pageTracker = _gat._getTracker("UA-6217271-15");
  pageTracker._trackPageview();
  } catch(err) {}
</script>
</body>
</html>