<form method=POST action="results.asp" name="loc">
    <h4>SEARCH BY SPECIFIC LOCATION</h4>
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="toc">Province/Region</div>
                <div style="margin-top: 4px;">
                    <div class="form-group input-group">
                        <select name="province" class="sub" size=7>
                            <option value="" selected>&lt;ALL&gt;</option>
                            <option value="AB">Alberta</option>
                            <option value="SK">Saskatchewan</option>
                            <option value="BC">British Columbia</option>
                            <option value="MB">Manitoba</option>
                            <option value="EC">Eastern Canada</option>
                            <option value="NC">Northern Canada</option>
                        </select>
                    </div>
                </div>
                <br>
                <div style="margin-left:40px;text-align:left;">
                    <input type="radio" name="location" value="surface" checked ID="Radio1">
                    Surface Location<br>
                    <input type="radio" name="location" value="bottom" ID="Radio2">
                    Bottom Hole<br>
                    <input type="image" src="/graphics/search.gif"
           name="PR" alt="Search" border=0 vspace=10>
                </div>
            </div>
            <div class="col-md-3">
                <div class="toc" >DLS</div>
                <div class="subbold">Township</div>
                <div class="row">
                    <div class="col-md-5">
                        <div class="sub">From:</div>
                        <div class="form-group input-group">
                            <select name="fromTownship" class="sub">
                                <option></option>
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                                <option>6</option>
                                <option>7</option>
                                <option>8</option>
                                <option>9</option>
                                <option>10</option>
                                <option>11</option>
                                <option>12</option>
                                <option>13</option>
                                <option>14</option>
                                <option>15</option>
                                <option>16</option>
                                <option>17</option>
                                <option>18</option>
                                <option>19</option>
                                <option>20</option>
                                <option>21</option>
                                <option>22</option>
                                <option>23</option>
                                <option>24</option>
                                <option>25</option>
                                <option>26</option>
                                <option>27</option>
                                <option>28</option>
                                <option>29</option>
                                <option>30</option>
                                <option>31</option>
                                <option>32</option>
                                <option>33</option>
                                <option>34</option>
                                <option>35</option>
                                <option>36</option>
                                <option>37</option>
                                <option>38</option>
                                <option>39</option>
                                <option>40</option>
                                <option>41</option>
                                <option>42</option>
                                <option>43</option>
                                <option>44</option>
                                <option>45</option>
                                <option>46</option>
                                <option>47</option>
                                <option>48</option>
                                <option>49</option>
                                <option>50</option>
                                <option>51</option>
                                <option>52</option>
                                <option>53</option>
                                <option>54</option>
                                <option>55</option>
                                <option>56</option>
                                <option>57</option>
                                <option>58</option>
                                <option>59</option>
                                <option>60</option>
                                <option>61</option>
                                <option>62</option>
                                <option>63</option>
                                <option>64</option>
                                <option>65</option>
                                <option>66</option>
                                <option>67</option>
                                <option>68</option>
                                <option>69</option>
                                <option>70</option>
                                <option>71</option>
                                <option>72</option>
                                <option>73</option>
                                <option>74</option>
                                <option>75</option>
                                <option>76</option>
                                <option>77</option>
                                <option>78</option>
                                <option>79</option>
                                <option>80</option>
                                <option>81</option>
                                <option>82</option>
                                <option>83</option>
                                <option>84</option>
                                <option>85</option>
                                <option>86</option>
                                <option>87</option>
                                <option>88</option>
                                <option>89</option>
                                <option>90</option>
                                <option>91</option>
                                <option>92</option>
                                <option>93</option>
                                <option>94</option>
                                <option>95</option>
                                <option>96</option>
                                <option>97</option>
                                <option>98</option>
                                <option>99</option>
                                <option>100</option>
                                <option>101</option>
                                <option>102</option>
                                <option>103</option>
                                <option>104</option>
                                <option>105</option>
                                <option>106</option>
                                <option>107</option>
                                <option>108</option>
                                <option>109</option>
                                <option>110</option>
                                <option>111</option>
                                <option>112</option>
                                <option>113</option>
                                <option>114</option>
                                <option>115</option>
                                <option>116</option>
                                <option>117</option>
                                <option>118</option>
                                <option>119</option>
                                <option>120</option>
                                <option>121</option>
                                <option>122</option>
                                <option>123</option>
                                <option>124</option>
                                <option>125</option>
                                <option>126</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="sub">To:</div>
                        <div class="form-group input-group">
                            <select name="toTownship" class="sub">
                                <option></option>
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                                <option>6</option>
                                <option>7</option>
                                <option>8</option>
                                <option>9</option>
                                <option>10</option>
                                <option>11</option>
                                <option>12</option>
                                <option>13</option>
                                <option>14</option>
                                <option>15</option>
                                <option>16</option>
                                <option>17</option>
                                <option>18</option>
                                <option>19</option>
                                <option>20</option>
                                <option>21</option>
                                <option>22</option>
                                <option>23</option>
                                <option>24</option>
                                <option>25</option>
                                <option>26</option>
                                <option>27</option>
                                <option>28</option>
                                <option>29</option>
                                <option>30</option>
                                <option>31</option>
                                <option>32</option>
                                <option>33</option>
                                <option>34</option>
                                <option>35</option>
                                <option>36</option>
                                <option>37</option>
                                <option>38</option>
                                <option>39</option>
                                <option>40</option>
                                <option>41</option>
                                <option>42</option>
                                <option>43</option>
                                <option>44</option>
                                <option>45</option>
                                <option>46</option>
                                <option>47</option>
                                <option>48</option>
                                <option>49</option>
                                <option>50</option>
                                <option>51</option>
                                <option>52</option>
                                <option>53</option>
                                <option>54</option>
                                <option>55</option>
                                <option>56</option>
                                <option>57</option>
                                <option>58</option>
                                <option>59</option>
                                <option>60</option>
                                <option>61</option>
                                <option>62</option>
                                <option>63</option>
                                <option>64</option>
                                <option>65</option>
                                <option>66</option>
                                <option>67</option>
                                <option>68</option>
                                <option>69</option>
                                <option>70</option>
                                <option>71</option>
                                <option>72</option>
                                <option>73</option>
                                <option>74</option>
                                <option>75</option>
                                <option>76</option>
                                <option>77</option>
                                <option>78</option>
                                <option>79</option>
                                <option>80</option>
                                <option>81</option>
                                <option>82</option>
                                <option>83</option>
                                <option>84</option>
                                <option>85</option>
                                <option>86</option>
                                <option>87</option>
                                <option>88</option>
                                <option>89</option>
                                <option>90</option>
                                <option>91</option>
                                <option>92</option>
                                <option>93</option>
                                <option>94</option>
                                <option>95</option>
                                <option>96</option>
                                <option>97</option>
                                <option>98</option>
                                <option>99</option>
                                <option>100</option>
                                <option>101</option>
                                <option>102</option>
                                <option>103</option>
                                <option>104</option>
                                <option>105</option>
                                <option>106</option>
                                <option>107</option>
                                <option>108</option>
                                <option>109</option>
                                <option>110</option>
                                <option>111</option>
                                <option>112</option>
                                <option>113</option>
                                <option>114</option>
                                <option>115</option>
                                <option>116</option>
                                <option>117</option>
                                <option>118</option>
                                <option>119</option>
                                <option>120</option>
                                <option>121</option>
                                <option>122</option>
                                <option>123</option>
                                <option>124</option>
                                <option>125</option>
                                <option>126</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="subbold">Range</div>
                <div class="row">
                    <div class="col-md-5">
                        <div class="sub">From:</div>
                        <div class="form-group input-group">
                            <select name="fromRange" class="sub">
                                <option></option>
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                                <option>6</option>
                                <option>7</option>
                                <option>8</option>
                                <option>9</option>
                                <option>10</option>
                                <option>11</option>
                                <option>12</option>
                                <option>13</option>
                                <option>14</option>
                                <option>15</option>
                                <option>16</option>
                                <option>17</option>
                                <option>18</option>
                                <option>19</option>
                                <option>20</option>
                                <option>21</option>
                                <option>22</option>
                                <option>23</option>
                                <option>24</option>
                                <option>25</option>
                                <option>26</option>
                                <option>27</option>
                                <option>28</option>
                                <option>29</option>
                                <option>30</option>
                                <option>31</option>
                                <option>32</option>
                                <option>33</option>
                                <option>34</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="sub">To:</div>
                        <div class="form-group input-group">
                            <select name="toRange" class="sub">
                                <option></option>
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                                <option>6</option>
                                <option>7</option>
                                <option>8</option>
                                <option>9</option>
                                <option>10</option>
                                <option>11</option>
                                <option>12</option>
                                <option>13</option>
                                <option>14</option>
                                <option>15</option>
                                <option>16</option>
                                <option>17</option>
                                <option>18</option>
                                <option>19</option>
                                <option>20</option>
                                <option>21</option>
                                <option>22</option>
                                <option>23</option>
                                <option>24</option>
                                <option>25</option>
                                <option>26</option>
                                <option>27</option>
                                <option>28</option>
                                <option>29</option>
                                <option>30</option>
                                <option>31</option>
                                <option>32</option>
                                <option>33</option>
                                <option>34</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="subbold">Meridian</div>
                <div class="row">
                    <div class="col-md-5">
                        <div class="sub">From:</div>
                        <div class="form-group input-group">
                            <select name="fromMeridian" class="sub">
                                <option></option>
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                                <option>6</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="sub">To:</div>
                        <div class="form-group input-group">
                            <select name="toMeridian" class="sub">
                                <option></option>
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                                <option>6</option>
                            </select>
                        </div>
                    </div>
                </div>
                <input type="image" src="/graphics/search.gif"
               name="DLS" alt="Search" border=0 vspace=10>
            </div>
            <div class="col-md-3">
                <div class="toc">NTS</div>
                <div class="subbold">Map Unit</div>
                <div class="row">
                    <div class="col-md-5">
                        <div class="sub">From:</div>
                        <div class="form-group input-group">
                            <select name="fromMapUnit" class="sub">
                                <option></option>
                                <option>82</option>
                                <option>92</option>
                                <option>93</option>
                                <option>94</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="sub">To:</div>
                        <div class="form-group input-group">
                            <select name="toMapUnit" class="sub">
                                <option></option>
                                <option>82</option>
                                <option>92</option>
                                <option>93</option>
                                <option>94</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="subbold">Map Unit Sub</div>
                <div class="row">
                    <div class="col-md-5">
                        <div class="sub">From:</div>
                        <div class="form-group input-group">
                            <select name="fromMapUnitSub" class="sub">
                                <option></option>
                                <option>A</option>
                                <option>B</option>
                                <option>C</option>
                                <option>D</option>
                                <option>E</option>
                                <option>F</option>
                                <option>G</option>
                                <option>H</option>
                                <option>I</option>
                                <option>J</option>
                                <option>K</option>
                                <option>L</option>
                                <option>M</option>
                                <option>N</option>
                                <option>O</option>
                                <option>P</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="sub">To:</div>
                        <div class="form-group input-group">
                            <select name="toMapUnitSub" class="sub">
                                <option></option>
                                <option>A</option>
                                <option>B</option>
                                <option>C</option>
                                <option>D</option>
                                <option>E</option>
                                <option>F</option>
                                <option>G</option>
                                <option>H</option>
                                <option>I</option>
                                <option>J</option>
                                <option>K</option>
                                <option>L</option>
                                <option>M</option>
                                <option>N</option>
                                <option>O</option>
                                <option>P</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="subbold">Map Sheet</div>
                <div class="row">
                    <div class="col-md-5">
                        <div class="sub">From:</div>
                        <div class="form-group input-group">
                            <select name="fromMapSheet" class="sub">
                                <option></option>
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                                <option>6</option>
                                <option>7</option>
                                <option>8</option>
                                <option>9</option>
                                <option>10</option>
                                <option>11</option>
                                <option>12</option>
                                <option>13</option>
                                <option>14</option>
                                <option>15</option>
                                <option>16</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="sub">To:</div>
                        <div class="form-group input-group">
                            <select name="toMapSheet" class="sub">
                                <option></option>
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                                <option>6</option>
                                <option>7</option>
                                <option>8</option>
                                <option>9</option>
                                <option>10</option>
                                <option>11</option>
                                <option>12</option>
                                <option>13</option>
                                <option>14</option>
                                <option>15</option>
                                <option>16</option>
                            </select>
                        </div>
                    </div>
                </div>
                <input type="image" name="NTS" src="/graphics/search.gif"
               border=0 alt="Search" vspace=10>
            </div>
        </div>
    </div>
    <div class="heading-block" style="margin-top: 1em;">SELECT A SORT OPTION</div>
    <input type="radio" name="sort" value="" checked>
    Location<br>
    <input type="radio" name="sort" value="Operator">
    Operator<br>
    <input type="radio" name="sort" value="Rig">
    Contractor and Rig
    <input type="radio" name="sort" value="Area">
    Area Name<br>
    <input type="radio" name="sort" value="Spud">
    Spud Date<br>
    <input type="radio" name="sort" value="Class">
    Well Class
    <input type="radio" name="sort" value="Status">
    Rig Status
    <div class="heading-block" style="margin-top: 1em;">SELECT RIG STATUS</div>
    <div style="margin-left: 6px;">
        <select name="status" size=6 class="sub">
            <option value="all" selected>&lt;ALL&gt;</option>
            <option value="active">ALL ACTIVE</option>
            <option value="DRILL">DRILL - Drilling</option>
            <option value="MIR">MIR - Moving in rig</option>
            <option value="RIGUP">RIGUP - Rigging up (setting up rig)</option>
            <option value="inactive">DOWN - Not active</option>
        </select>
    </div>
    <br>
</form>
