</div>
<div id="lower-menu" class="menu-text">
<a href="http://www.riglocator.ca" target="_blank">Rig Home</a> 
</div>

<div id="footer-block" class="dateline" style="text-align: center;">
 &copy; <% = Year(Date) %>
<a href="/common/copyright.asp">Copyright JuneWarren-Nickle's Energy Group</a>. All rights reserved.<br>
</div>
<script type="text/javascript">
  var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
  document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
  try {
  var pageTracker = _gat._getTracker("UA-6217271-15");
  pageTracker._trackPageview();
  } catch(err) {}
</script>
